(
SELECT STATION.CITY, LENGTH(STATION.CITY)
FROM STATION
ORDER BY LENGTH(STATION.CITY) ASC, STATION.CITY ASC
LIMIT 0,1
)
UNION
(
SELECT STATION.CITY, LENGTH(STATION.CITY)
FROM STATION
ORDER BY LENGTH(STATION.CITY) DESC, STATION.CITY ASC
LIMIT 0,1
)
